"""change property value max length

Revision ID: b2ecc00d87d5
Revises: ef10c32133bb
Create Date: 2024-07-09 12:26:42.304062

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b2ecc00d87d5"
down_revision: Union[str, None] = "ef10c32133bb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_event_properties",
        "value",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=80),
        existing_nullable=False,
    )
    op.alter_column(
        "user_properties",
        "value",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=80),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_properties",
        "value",
        existing_type=sa.String(length=80),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    op.alter_column(
        "user_event_properties",
        "value",
        existing_type=sa.String(length=80),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
